baseURL = 'https://alexmoore.dev/'
languageCode = 'en-GB'
title = 'Alex Moore - adventures in infrastructure'
theme = 'hugo-profile'

[services]
  [services.googleAnalytics]
    id = "G-7QKE2X6E8M"

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    title = "Blog posts"
    url = "/blogs"
    weight = 1

[params]
  favicon = "/images/fav.png"
  author = "Alex Moore"
  keywords = "cloud, IT infrastructure, storage, compute, networking, Google Cloud, GCP, AWS, Azure, AI, ML, GPU, TPU"
  [params.hero]
    enable = true
    intro = "Hi, my name is"
    title = "Alex Moore."
    subtitle = "Adventures in infrastructure..."
    content = "With over 20 years in the tech industry, I've journeyed from hands-on engineering to leading teams at the forefront of cloud and AI. I'm passionate about demystifying technology and empowering others to build innovative solutions. When I'm not exploring the digital frontier, you might find me on a ski slope or a badminton court."
    image = "/images/me.png"
    [params.hero.button]
      enable = false
  [params.about]
    enable = true
    title = "About Me"
    image = "/images/me.png"
    content = """
With over two decades of experience in the technology industry, I've had the privilege of working with a diverse range of technologies and platforms. My journey has taken me from the early days of the internet to the cutting edge of AI and cloud computing. I'm a firm believer in the power of technology to solve real-world problems and I'm passionate about helping organizations leverage the cloud to its full potential.

I've had the opportunity to wear many hats throughout my career, from a hands-on engineer to a technology leader. This has given me a unique perspective on the challenges and opportunities that come with digital transformation. I enjoy working with customers to understand their needs and helping them design and implement solutions that are not only technically sound but also deliver real business value.

When I'm not working, I enjoy spending time with my family, running, skiing, and playing badminton. I'm also a keen supporter of STEM education and enjoy mentoring the next generation of technology leaders.
"""
    [params.about.skills]
      enable = true
      title = "Here are a few technologies I've been working with recently:"
      items = ["Google Cloud (GCP)", "Amazon Web Services (AWS)", "Microsoft Azure", "Kubernetes", "Docker", "Terraform", "CI/CD", "Python", "Go", "AI/ML", "TPU/GPU", "Slurm"]
  [params.footer]
    [params.footer.recentPosts]
      path = "blogs"
      count = 3
      title = "Recent Posts"
      enable = true
      disableFeaturedImage = false
    [params.footer.socialNetworks]
      github = "https://github.com/alexjmoore"
      linkedin = "https://www.linkedin.com/in/alexjmoore/"
      bluesky = "https://bsky.app/profile/alexmoore.dev"
